parameters:
  currency_rates:
    EUR:
      USD: 1.0952
      GBP: 0.85
      JPY: 145.30
      CHF: 0.98
      CAD: 1.34
    USD:
      EUR: 0.912
      GBP: 0.77
      JPY: 132.45
      CHF: 0.90
      CAD: 1.22
    GBP:
      EUR: 1.18
      USD: 1.30
      JPY: 172.00
      CHF: 1.17
      CAD: 1.58
    JPY:
      EUR: 0.0069
      USD: 0.0075
      GBP: 0.0058
      CHF: 0.0068
      CAD: 0.0092
    CHF:
      EUR: 1.02
      USD: 1.11
      GBP: 0.85
      JPY: 147.0
      CAD: 1.35
    CAD:
      EUR: 0.75
      USD: 0.82
      GBP: 0.63
      JPY: 109.1
      CHF: 0.74
