version: '3.8'
services:
  php:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    tty: true
    command: >
      sh -c "composer install &&
             php -S 0.0.0.0:8000 -t public"
